
spring:
  profiles:
    active: test
  application:
    name: boot-server
  messages:
    basename: i18n/messages
    encoding: utf-8
  mvc:
      date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #test-while-idle: false
      #test-on-borrow: true
      #test-on-return: false
      validation-query: SELECT 1 FROM DUAL
      stat-view-servlet:
        login-username: admin
        login-password: admin123
      filter:
        stat:
          enabled: true
        config:
          enabled: true

com:
  example:
    hello: hello
    world: world

logging:
  file:
    max-size: 10MB
    max-history: 1

info:
  author: liaowei
  version: @project.version@
  name: @project.artifactId@a

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

mapper:
  not-empty: false
  identity: MYSQL

mybatis:
  configuration:
    local-cache-scope: STATEMENT
    jdbc-type-for-null: NULL
    default-statement-timeout: 15

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

swagger:
  enabled: true
  base-package: com.example.boot.server
  title: "Boot Server 接口列表"
  description: "Boot Server 接口列表描述了所有对外提供服务的接口信息"
  version: v0.0.1
  contact:
    name: liaowei
    url: http://www.liaowei.net.cn
    email: 24591106@qq.com
